# collections/requirements.yml
# Pin collection versions for reproducible EE builds.
# Replace the version values with the exact versions you valida environment.
---
collections:
  - name: netbox.netbox
    version: ">=3.10.0"
  - name: ansible.netcommon
    version: ">=5.0.0"
  - name: community.network
    version: ">=5.0.0"
  - name: cisco.ios
    version: ">=5.0.0"
  - name: cisco.iosxr
    version: ">=5.0.0"
  - name: cisco.nxos
    version: ">=5.0.0"
  - name: arista.eos
    version: ">=5.0.0"
  - name: junipernetworks.junos
    version: ">=5.0.0"
  - name: community.network
    version: ">=5.0.0"
  - name: ansible.netcommon
    version: ">=5.0.0"
